name: GitHub Data Pipeline

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  github_repos_pipeline:
    name: GitHub Repos Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: main
        uses: hooopo/repo-track-pipeline@main
        with:
          access-token: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          database-url: ${{ secrets.DATABASE_URL }}/${{ secrets.GITHUB_REPO_DATABASE || 'github_repos' }}
          repo-full-name: ${{ secrets.REPO_FULL_NAME }}

  github_personal_pipeline:
    name: GitHub Personal Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: main
        uses: hooopo/oh-my-github-pipeline@main
        with:
          access-token: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          database-url: ${{ secrets.DATABASE_URL }}/${{ secrets.GITHUB_PERSONAL_DATABASE || 'github_personal' }}
          user-login: ${{ secrets.USER_LOGIN || github.repository_owner }}
